#!/bin/bash
echo "Script para limpar autenticação do app"
echo ""
echo "Execute no terminal ADB:"
echo ""
echo "adb shell"
echo "run-as com.mobilebridgeapp"
echo "cd /data/data/com.mobilebridgeapp/files"
echo "rm -f RCTAsyncLocalStorage_V1/*"
echo "exit"
echo "exit"
echo ""
echo "Ou simplesmente desinstale e reinstale o app:"
echo "adb uninstall com.mobilebridgeapp"
